export function aboutIntroductionHTML() {
  return `<div class="text-introduction">
<h2 class="book-title">Wisdom of the Wolof Sages</h2>
<p class="book-subtitle">A Collection of Proverbs from Senegal translated and explained in English</p>
<p class="book-edition">Richard Shawyer · First edition · August 2009</p>
<p>This book brings together 743 Wolof proverbs with English translations, explanations and related sayings. Its subjects range from work and patience to friendship, speech and responsibility. It offers a way to study the language and discuss the situations in which a proverb might be used.</p>
<dl class="book-facts"><div><dt>Proverbs</dt><dd>743</dd></div><div><dt>Topics</dt><dd>207</dd></div><div><dt>PDF pages</dt><dd>101</dd></div><div><dt>Languages</dt><dd>Wolof / English</dd></div></dl>
<div class="about-actions"><a href="#browse">Read the collection <span aria-hidden="true">→</span></a><a href="#values">Explore the values</a><a href="original.pdf" target="_blank" rel="noopener">Open original PDF<span class="sr-only"> (opens in a new tab)</span></a></div>
<nav class="about-contents" aria-label="About this text sections"><a href="#about-author">Compiler &amp; contributors</a><a href="#about-sources">The book’s sources</a><a href="#about-reading">How to read it</a><a href="#study-sources">Study aids</a><a href="#about-bibliography">Bibliography</a></nav>

<h2 id="about-author">Richard Shawyer and the contributors</h2>
<p>The title page credits <strong>Dr. Richard Shawyer</strong>. He signs the foreword <strong>Richard Shawyer (dit Musaa Sarr)</strong>, identifying the Wolof name by which he is also known. His role here is compiler and editor of a collection drawn from earlier sources. The traditional sayings themselves are not his individual compositions. In the foreword, he presents proverbs as useful for teaching and for addressing difficulties in relationships. <a href="original.pdf#page=2" target="_blank" rel="noopener">Foreword, p. 2<span class="sr-only"> (opens in a new tab)</span></a>.</p>
<p>Shawyer specifically thanks <strong>Maam Daoud Wade</strong> for translating about 100 proverbs. He also credits John Bardsley, Galen Currah, Graham Keen and Jeanette Lee with proofreading and suggestions. Those acknowledgements matter: the English edition is a collaborative compilation. <a href="original.pdf#page=2" target="_blank" rel="noopener">Acknowledgements in the foreword<span class="sr-only"> (opens in a new tab)</span></a>.</p>
<p>His other documented work includes the 1999 guide <a href="https://currah.download/pages/wolofresources/language/how_to_learn_wolof.htm" target="_blank" rel="noopener"><cite>Learning Wolof Can be Fun</cite><span class="sr-only"> (archived text; opens in a new tab)</span></a> and a <a href="https://currah.download/pages/wolofresources/language/sounds.htm" target="_blank" rel="noopener">Wolof pronunciation guide<span class="sr-only"> (archived text; opens in a new tab)</span></a>. The <a href="https://currah.download/pages/wolofresources/language/resources.htm" target="_blank" rel="noopener">Wolof Resources archive<span class="sr-only"> (opens in a new tab)</span></a> also lists his 2001 grammar manual and a separate collection of 2,750 proverbs without translations or explanations. That larger collection is a different work from the 743-proverb English edition used here.</p>

<h2 id="about-sources">A collection built from other collections</h2>
<p>Shawyer explicitly describes the book as a compilation. Its bibliography draws on proverb collections, dictionaries, literacy materials and studies of Wolof life. Examples include <a href="#reference-2"><cite>Proverbes Wolof</cite> by Mame Thierno Cissé, Mamadou Gueye and Mangone Touré (CLAD, 1982)</a>, <a href="#reference-7">Aram Faal’s orthographic dictionary (2000)</a>, and <a href="#reference-15">Assane Sylla’s <cite>La Philosophie Morale des Wolof</cite> (IFAN, 1994)</a>. Earlier grammars by Dard and Boillat are also listed. <a href="original.pdf#page=99" target="_blank" rel="noopener">Bibliography, p. 99<span class="sr-only"> (opens in a new tab)</span></a>.</p>
<p>The numbers attached to entries point back to that bibliography; one proverb may have several sources or variants. The topic arrangement is the compiler’s: in the foreword he invites readers to suggest better headings and classifications. The book should therefore be read as a particular selection and arrangement, rather than a complete catalogue of Senegalese thought.</p>

<h2 id="about-reading">Reading the different parts of an entry</h2>
<dl class="text-layers"><div><dt>Wolof proverb and variants</dt><dd>The saying as printed in the source, including alternative versions where supplied.</dd></div><div><dt>English translation</dt><dd>The book’s literal rendering. It can retain an image or expression that needs further explanation.</dd></div><div><dt>Explanation and English parallels</dt><dd>The book’s account of use and meaning, sometimes with an example situation. An English parallel is an approximate comparison, not another literal translation.</dd></div><div><dt>Biblical quotations</dt><dd>Passages from the New International Version appear throughout the book. They are part of this edition’s Christian editorial framing, separate from the Wolof proverb itself.</dd></div></dl>
<p class="source-line">The compiler explains these distinctions in the <a href="original.pdf#page=2" target="_blank" rel="noopener">foreword, p. 2<span class="sr-only"> (opens in a new tab)</span></a>.</p>
<p>A useful reading question is: <strong>Who might say this, to whom, and in what situation?</strong> Compare the literal image with the explanation and any variants. The source includes assumptions about gender, age and social status that readers may question. A printed proverb is material for discussion; it does not establish what every Senegalese person believes.</p>

<h2>This digital edition</h2>
<p>The collection preserves all 743 numbered entries, their source wording, variants, explanations and page links. Search, practice questions, recordings, word notes and the Values view have been added for this website. The Values explanations are new, sourced teaching interpretations; they are not translations or categories supplied by Shawyer.</p>
<p>This introduction draws on the supplied book’s title page, foreword and bibliography, checked against the <a href="https://currah.download/pages/wolofresources/language/download/proverbs.pdf" target="_blank" rel="noopener">archived public copy<span class="sr-only"> (opens in a new tab)</span></a>, and on Shawyer’s language-learning materials linked above. The biography is limited to information those sources establish.</p>
</div>`;
}
